version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map port 3000 on host to port 80 on container
    depends_on:
      - backend  # Ensure backend service is started first

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Map port 5000 on host to port 5000 on container
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - database  # Assuming you have a database service defined

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3306:3306"  # Map port 3306 on host to port 3306 on container
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

